# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

#
# This action runs whenever code is pushed to the main branch,
# as well as twice daily to ensure that the app remains valid.
#

name: App Validation
on:
  push:
    branches: 
      - '*'

jobs:
  Validate:
    runs-on: macos-11
    timeout-minutes: 20
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

    steps:
      - name: Show Info
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "TAG: ${{ github.event.inputs.branch }}"
          echo "ORGNAME: ${{ github.event.pull_request.head.user.login }}"
          echo "ORGNAME=${{ github.event.pull_request.head.user.login }}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: "Validate App Org: ${{ env.ORGNAME }}"
        run: xcrun swift run -- fairtool validate --verbose true --hub github.com/appfair --token "${{ secrets.GITHUB_TOKEN }}" --org "${{ env.ORGNAME }}" --project .

      - name: Test Swift Package
        run: xcrun swift test

      - name: Build macOS
        run: xcodebuild build -workspace App.xcworkspace -configuration Release -scheme "Application" -sdk 'macosx' CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=YES

      - name: Build iOS
        run: xcodebuild build -workspace App.xcworkspace -configuration Release -scheme "Application" -sdk 'iphoneos' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO


